# Generated by Django 4.0.6 on 2022-08-05 13:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstcoach_name', models.CharField(max_length=15)),
                ('lastcoach_name', models.CharField(max_length=15)),
                ('coach_email', models.EmailField(max_length=254)),
                ('coach_phonenumber', models.CharField(max_length=20)),
                ('coach_gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('coach_address', models.TextField()),
                ('coach_nationality', models.CharField(max_length=20)),
                ('coach_pic', models.ImageField(upload_to='images/')),
                ('coach_team', models.CharField(max_length=15)),
                ('coach_title', models.CharField(choices=[('Assistant coach', 'Assistant coach'), ('Head coach', 'Head coach')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('leader_email', models.EmailField(max_length=254)),
                ('leader_phonenumber', models.CharField(max_length=20)),
                ('leader_gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('leader_address', models.TextField()),
                ('leader_nationality', models.CharField(max_length=20)),
                ('leader_pic', models.ImageField(upload_to='uploads/')),
                ('leader_title', models.CharField(choices=[('Federation leader', 'Federation leader'), ('Scout ', 'Scout')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reffirst_name', models.CharField(max_length=15)),
                ('reflast_name', models.CharField(max_length=15)),
                ('refemail', models.EmailField(max_length=254)),
                ('ref_pic', models.ImageField(upload_to='uploads/')),
                ('refphone_number', models.CharField(max_length=20)),
                ('refgender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('refddress', models.TextField()),
                ('refationality', models.CharField(max_length=20)),
                ('ref_title', models.CharField(choices=[('Assistant coach', 'Assistant coach'), ('Head coach', 'Head coach')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('no_players', models.IntegerField()),
                ('list_player', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=8)),
                ('team_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('player_pic', models.ImageField(upload_to='uploads/')),
                ('Phone_number', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('age', models.PositiveSmallIntegerField()),
                ('address', models.TextField()),
                ('nationality', models.CharField(max_length=20)),
                ('employed', models.BooleanField()),
                ('players_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='New_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(choices=[('Federation leader', 'Federation leader'), ('Scout ', 'Scout')], max_length=20)),
                ('message', models.TextField()),
                ('news_image', models.ImageField(upload_to='uploads/')),
                ('repoter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.leader')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.TextField()),
                ('match_datetime', models.DateTimeField(auto_now_add=True)),
                ('match_location', models.CharField(max_length=20)),
                ('match_pic', models.ImageField(upload_to='uploads/')),
                ('match_video', models.FileField(upload_to='uploads/')),
                ('match_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.referee')),
                ('match_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.new_report')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixtures', models.FileField(upload_to='uploads/')),
                ('date', models.DateField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.leader')),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_name', models.CharField(max_length=30)),
                ('event_awarded', models.CharField(max_length=30)),
                ('item_award', models.CharField(max_length=30)),
                ('playerward_pic', models.ImageField(upload_to='uploads/')),
                ('player_awarded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sportsapp.player')),
            ],
        ),
    ]
