# Generated by Django 4.0.6 on 2022-08-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medic',
        ),
    ]
