# Generated by Django 4.0.6 on 2022-08-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0002_delete_medic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medic_name', models.CharField(max_length=20)),
                ('medic_pic', models.ImageField(upload_to='uploads/')),
                ('medic_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sportsapp.team')),
            ],
        ),
    ]
